Assignment 2 updated to use new dataset
UofT-DSI/applying_statistical_concepts pull request #105
Opened 2024-09-28 21:46 UTC by danielrazavi

## What changes are you trying to make? (e.g., Adding or removing code, refactoring existing code, adding reports)

- Updated the dataset in **Assignment 2** from the **Diabetes dataset** to the **Auto MPG dataset**.
- Refactored data exploration, data splitting, model fitting, and evaluation code to align with the new dataset.
- Revised assignment questions to better fit the **Auto MPG dataset** context.
- Updated Markdown descriptions to reflect the new dataset and added new questions to keep the assignment fresh.

## How were these changes tested?

- Ran all cells and tested for errors, ensuring that each section worked as intended.
- Verified that the training and testing data splits were correctly executed with appropriate shapes.
- Evaluated model output metrics (e.g., RMSE) to ensure the logic and performance were aligned with the objectives of the assignment.

## Checklist
- [x] I can confirm that my changes are working as intended.

2024-09-28 21:59 UTC, juliagallucci submitted a review, later dismissed

2024-09-30 01:39 UTC, HongleiXie requested changes
Hi thanks for the quick turnaround. I added a couple of comments for review:
1. In Q2 (iii) `What is the (implied) null hypothesis? What is the (implied) alternative hypothesis?` -- I think we should remove this question or substitute it with another one since we don't cover hypothesis testing in this cohort (we did for last cohort)
2. Just be consistent with the slides/notebooks shown in class about the language, can we change to `RMSPE` instead in `Q4 - Model Evaluation`?

2024-09-30 13:51 UTC, danielrazavi commented
1. Yes
2. Yes

2024-09-30 14:16 UTC, juliagallucci approved these changes

2024-09-30 20:34 UTC, HongleiXie approved these changes
Looks good! Thanks for the revision!

2024-09-30 20:36 UTC, merged