Finalizing the Third Assignment.
UofT-DSI/applying_statistical_concepts pull request #122
Opened 2024-10-07 01:45 UTC by danielrazavi

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
I added some more questions to encourage deeper analysis of the visualizations and tweaked other sections to improve clarity and engagement for Assignment 3.

## How were these changes tested?
The changes were tested in the `dsi_participant` conda environment to ensure full execution without errors.

## A reference to a related issue in your repository (if applicable)
N/A

## Checklist
- [X] I can confirm that my changes are working as intended

2024-10-07 03:14 UTC, HongleiXie requested changes
Left a few comments for consideration:
1. I think we should add some explanation about this labelled dataset while they are asked to perform a clustering task. Seems to be confusing. Suggest to remove `Target Variable` part in markdown. And add more reasoning why we choose k=3
2. Suggest to remove the question asking them to write codes to plots. Instead we should provide codes and only let them answer the following questions. Because writing codes to plot is not covered in class.
3. There is a typo in the very last assignment submission guide, specifically the branch name should be assignment 3 instead of assignment 1

2024-10-07 18:55 UTC, juliagallucci submitted a review, later dismissed

2024-10-07 21:20 UTC, HongleiXie approved these changes
LGTM! Thanks!

2024-10-08 13:16 UTC, KasraVakiloroayaei commented
Looks good to me!

2024-10-08 13:23 UTC, merged